# Generated by Django 2.2 on 2019-05-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190424_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
