# Generated by Django 2.2 on 2019-04-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        ('cards', '0002_auto_20190424_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sideboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sideboard_deck', to='decks.Deck')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_deck', to='decks.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='SideboardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sideboarditem_card', to='cards.Card')),
                ('sideboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sideboarditem_sideboard', to='sideboards.Sideboard')),
            ],
        ),
    ]
