# Generated by Django 2.2 on 2019-04-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideboard',
            name='slug',
            field=models.SlugField(default='sdfsdf', max_length=100),
            preserve_default=False,
        ),
    ]
