# Generated by Django 2.2 on 2019-04-28 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sideboards', '0003_auto_20190428_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideboard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sideboard_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
