# Generated by Django 2.2 on 2019-04-28 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_auto_20190428_1211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sideboards', '0004_sideboard_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sideboard',
            unique_together={('owner', 'deck', 'opponent')},
        ),
    ]
