# Generated by Django 2.2 on 2019-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideboards', '0005_auto_20190428_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideboarditem',
            name='delta',
            field=models.IntegerField(default=0),
        ),
    ]
