# Generated by Django 2.2 on 2019-05-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0009_auto_20190519_2109'),
        ('sideboards', '0006_auto_20190505_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideboarditem',
            name='decklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sideboarditem_decklistitem', to='decks.DeckListItem'),
        ),
    ]
