# Generated by Django 2.2 on 2019-04-24 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_auto_20190424_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=255)),
                ('archetype', models.CharField(choices=[('AGGRO', 'Aggro'), ('COMBO', 'Combo'), ('CONTROL', 'Control'), ('Midrange', 'Midrange'), ('Tempo', 'Tempo'), ('OTHER', 'Other')], max_length=200)),
                ('legality', models.CharField(choices=[('STANDARD', 'Standard'), ('MODERN', 'Modern')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeckListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_sideboard', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decklistitem_card', to='cards.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decklistitem_deck', to='decks.Deck')),
            ],
        ),
    ]
