# Generated by Django 2.2 on 2019-04-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_emblem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['deck_name']},
        ),
        migrations.AlterField(
            model_name='deck',
            name='archetype',
            field=models.CharField(choices=[('AGGRO', 'Aggro'), ('COMBO', 'Combo'), ('CONTROL', 'Control'), ('MIDRANGE', 'Midrange'), ('TEMPO', 'Tempo'), ('OTHER', 'Other')], max_length=200),
        ),
    ]
