# Generated by Django 2.2 on 2019-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20190425_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=models.SlugField(default='dsfgfdg'),
            preserve_default=False,
        ),
    ]
