# Generated by Django 2.2 on 2019-05-05 18:30

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_deck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='archetype',
            field=models.CharField(choices=[('AGGRO', 'Aggro'), ('COMBO', 'Combo'), ('CONTROL', 'Control'), ('MIDRANGE', 'Midrange'), ('TEMPO', 'Tempo'), ('OTHER', 'Other')], max_length=200, verbose_name='Archetype'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='emblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emblem_card', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='legality',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('MODERN', 'Modern')], max_length=200, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='deck_name'),
        ),
    ]
