# Generated by Django 2.2 on 2019-05-19 13:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_auto_20190505_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_empty',
            field=models.BooleanField(default=False, help_text='An empty deck is used to represent an opponents deck, it has no cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255)),
        ),
    ]
